GET http://localhost:3000/posts

###
POST http://localhost:3000/login
Content-Type: application/json

{
    "username":"Sree Harsha",
    "password":"passwo"
}

### 
POST https://cyberfusionapi.onrender.com/hotels
Content-Type: application/json

{
      "name": "VitalBoutique Hotel Zurzacherhof",
      "address": "Dr. Martin Erb-Strasse 5, Bad Zurzach, Zurich (region), Switzerland",
      "price": 260,
      "discount": 0.5,
      "rating": 4.3,
      "image": "./images/Switzerland/Zurich/5.jpg",
      "region": "Zurich",
      "country": "Switzerland"
}