GET http://localhost:3000/posts

###
POST http://localhost:3000/login
Content-Type: application/json

{
    "username":"Sree Harsha",
    "password":"passwo"
}

### 
POST http://localhost:3000/hotels
Content-Type: application/json

{
      "name": "HOTEL aarau-WEST",
      "address": "Muhenstrasse 58, Oberentfelden, Aargau, Switzerland",
      "price": 216,
      "discount": 0.5,
      "rating": 4.5,
      "image": "./images/Switzerland/Aargau/5.jpg",
      "region": "Aargau",
      "country": "Switzerland"
}

### 
GET http://localhost:3000/hotels
